export const PREPARE_KLIP_REQUEST = 'PREPARE_KLIP_REQUEST'
export const PREPARE_KLIP_SUCCESS = 'PREPARE_KLIP_SUCCESS'
export const PREPARE_KLIP_FAILURE = 'PREPARE_KLIP_FAILURE'

export const GET_RESULT_KLIP_REQUEST = 'GET_RESULT_KLIP_REQUEST'
export const GET_RESULT_KLIP_SUCCESS = 'GET_RESULT_KLIP_SUCCESS'
export const GET_RESULT_KLIP_FAILURE = 'GET_RESULT_KLIP_FAILURE'

export const GET_CARD_KLIP_REQUEST = 'GET_CARD_KLIP_REQUEST'
export const GET_CARD_KLIP_SUCCESS = 'GET_CARD_KLIP_SUCCESS'
export const GET_CARD_KLIP_FAILURE = 'GET_CARD_KLIP_FAILURE'